application: on-i-channels
version: 1
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js
- url: /mapreduce(/.*)?
  script: mapreduce/main.py
- url: /.*
  script: main.py

builtins:
- datastore_admin: on
- remote_api: on
